### ISSUE TITLE
Width prior is different from MATLAB version

### ISSUE THREAD

**Issue by dekuenstle** [wichmann-lab/python-psignifit#150] opened 2024-10-07 10:07 UTC
There is most likely a bug in the implementation of the width prior, which might explain the slight differences in CIs between the MATLAB and Python implementations. 

@guillermoaguilar Could you please add the screenshots?

**Comment by guillermoaguilar** [comment] 2024-10-07 10:28
MATLAB priors:

![Screenshot from 2024-10-07 12-22-25](https://github.com/user-attachments/assets/7382421a-a313-48bf-a123-e188f8411444)

Python priors:
![Screenshot from 2024-10-07 12-22-44](https://github.com/user-attachments/assets/53b9c9b8-5d0e-4d75-9acd-93fd7e4f2053)

Width prior is different, particularly on the left side.

**Comment by guillermoaguilar** [comment] 2024-10-08 17:21
OK after breaking my head I found that this may not a bug at all. I explain:

- I checked that priors are all exactly the same. Plots were different because the bounds where to evaluate the priors is different between matlab and python. In python we do two grids, one course and later one tighter.  The tigher overwrites the course one. Only the tighter grid gets returned
The two plots above are ran using the same parameters *except* that

**Comment by guillermoaguilar** [comment] 2024-10-08 17:30
Now, the two plots above were actually ran using the same parameters *except* that in the python one we pass manually the *stimulus_range*.  I overlooked this detail before.

If I do the same in the MATLAB version, the plot changes accordingly.


![Screenshot from 2024-10-08 19-29-14](https://github.com/user-attachments/assets/26c59f8b-92e8-4f46-bf5c-d5d2a55e1e1c)


So, the width prior implementation is actually OK. No bug.

**Comment by guillermoaguilar** [comment] 2024-10-08 18:49
I then close this issue.

**Closed by guillermoaguilar** 2024-10-08 18:49 UTC
